- hosts: terraform-ansible
  tasks:
    - name: Install python3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: Install deps in virtualenv (Django and Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Setup project
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
    - name: Update settings.py
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regex: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes